locals {
  etcd_nodes_count = 1
  etcd_nodes       = [for i in range(local.etcd_nodes_count) : "etcd${i}"]
}

resource "google_service_account" "etcd" {
  for_each     = toset(local.etcd_nodes)
  account_id   = "${each.value}-sa"
  display_name = "Service Account for etcd VM Instance"
}

resource "google_compute_instance" "etcd" {
  for_each     = toset(local.etcd_nodes)
  name         = each.value
  machine_type = "e2-standard-2"
  zone         = local.zone

  tags = ["role", each.value]

  boot_disk {
    initialize_params {
      image = "projects/debian-cloud/global/images/debian-13-trixie-v20260908"
      labels = {
        role = each.value
      }
    }
  }

  network_interface {
    network = "default"

    access_config {
      // Ephemeral public IP
    }
  }

  metadata = {
    enable-oslogin = "TRUE"
  }

  metadata_startup_script = <<-EOT
    #!/bin/bash
    set -euxo pipefail
    apt update && \
    apt install -y ansible git && \
    git clone https://github.com/andregri/ansible-roles.git /tmp/ansible-roles && \
    cd /tmp/ansible-roles && \
    ansible --inventory localhost, all --connection local --become --module-name include_role --args name=etcd
  EOT

  service_account {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    email  = google_service_account.etcd[each.key].email
    scopes = ["cloud-platform"]
  }

  provisioner "local-exec" {
    when    = create
    command = "sed -i '' '/^${each.key}/d' \"$HOME/.ssh/known_hosts\""
  }
}

resource "local_file" "req_csr_json" {
  filename = "${path.module}/config/req-csr.json"
  content = jsonencode({
    CN : "etcd",
    hosts : concat(["localhost", "127.0.0.1"], [for node in local.etcd_nodes : google_compute_instance.etcd[node].network_interface.0.network_ip]),
    key : {
      algo : "rsa",
      size : 2048
    },
    names : [
      {
        "O" : "autogenerated",
        "OU" : "etcd cluster",
        "L" : "US"
      }
    ]
  })
}

resource "local_file" "ca_config_json" {
  filename = "${path.module}/config/ca-config.json"
  content = jsonencode({
    "signing" : {
      "default" : {
        "usages" : [
          "signing",
          "key encipherment",
          "server auth",
          "client auth"
        ],
        "expiry" : "876000h"
      }
    }
  })
}

resource "local_file" "req_ca_json" {
  filename = "${path.module}/config/ca-csr.json"
  content = jsonencode({
    "CN" : "Autogenerated CA",
    "key" : {
      "algo" : "rsa",
      "size" : 2048
    },
    "names" : [
      {
        "O" : "Honest Achmed's Used Certificates",
        "OU" : "Hastily-Generated Values Divison",
        "L" : "San Francisco",
        "ST" : "California",
        "C" : "US"
      }
    ],
    "ca" : {
      "expiry" : "876000h"
    }
  })
}

resource "null_resource" "gen_ca_cert" {
  depends_on = [local_file.req_ca_json]

  provisioner "local-exec" {
    command = <<-EOT
      mkdir -p certs && \
      cfssl gencert -initca config/ca-csr.json | cfssljson -bare certs/ca
    EOT
    when    = create
  }

  triggers = {
    csr = join(",",[local_file.req_ca_json.content_sha256, local_file.ca_config_json.content_sha256, local_file.req_csr_json.content_sha256])
  }
}

resource "null_resource" "gen_server_cert" {
  for_each = toset(local.etcd_nodes)

  depends_on = [local_file.req_ca_json, local_file.ca_config_json, local_file.req_csr_json, null_resource.gen_ca_cert]

  provisioner "local-exec" {
    command = <<-EOT
      cfssl gencert \
        -ca certs/ca.pem \
        -ca-key certs/ca-key.pem \
        -config config/ca-config.json \
        config/req-csr.json | cfssljson -bare certs/${each.value}
    EOT
    when    = create
  }

  triggers = {
    csr = join(",",[local_file.req_ca_json.content_sha256, local_file.ca_config_json.content_sha256, local_file.req_csr_json.content_sha256])
  }
}

resource "null_resource" "gen_peer_cert" {
  for_each   = toset(local.etcd_nodes)

  depends_on = [local_file.req_ca_json, local_file.ca_config_json, local_file.req_csr_json, null_resource.gen_ca_cert]
  
  provisioner "local-exec" {
    command = <<-EOT
      cfssl gencert \
        -ca certs/ca.pem \
        -ca-key certs/ca-key.pem \
        -config config/ca-config.json \
        config/req-csr.json | cfssljson -bare certs/peer-${each.value}
    EOT
    when    = create
  }

  triggers = {
    csr = join(",",[local_file.req_ca_json.content_sha256, local_file.ca_config_json.content_sha256, local_file.req_csr_json.content_sha256])
  }
}
